Repository GSG-CF05/FinanceApp_Team7, pull requests merged in 2022-02, with the labels that each got.

#2 Create file structure
  2homepage/2homepage.css
  2homepage/2homepage.html
  3walletpage/3walletpage.css
  3walletpage/3walletpage.html
  4sendmoneypage/4sendmoneypage.css
  4sendmoneypage/4sendmoneypage.html
  images/Background.png
  images/Battery.png
  images/Cellular Connection.png
  images/Currency Crush Coins.png
  images/Currency Crush Graphs.png
  images/Home Indicator.png
  images/Icon (1).png
  images/Icon (2).png
  images/Icon (3).png
  images/Icon (4).png
  images/Icon (5).png
  images/Icon (6).png
  images/Icon.png
  images/Logo (1).png
  images/Logo (2).png
  images/Logo.png
  images/Profile Pic (1).png
  images/Profile Pic.png
  images/Right Icon.png
  images/Vector (1).png
  images/Vector (2).png
  images/Vector (3).png
  images/Vector.png
  images/Wifi.png
  images/account-user.png
  images/more-overflow-menu-horiz.png
  images/statistics.png
  images/wallet.png
  index.html
  style.css
Labels: awaiting-review, approved

#9 3 create the header
  2homepage/2homepage.css
  2homepage/2homepage.html
  2homepage/media.css
  images/header-home.gif
  images/more.png
Labels: approved

#11 design a mobile view for the landing page with html & css
  .vscode/settings.json
  index.html
  style.css
Labels: approved

#17 Create the pay section
  2homepage/2homepage.css
  2homepage/2homepage.html
  2homepage/media.css
Labels: awaiting-review

#16 create a responsive deign with media query
  index.html
  medialandingpage.css
Labels: awaiting-review

#20 7 create the footer
  2homepage/2homepage.css
  2homepage/2homepage.html
  2homepage/media.css
  images/Favourites.png
  images/Frame.png
Labels: approved

#19 edit the image height for my interface
  medialandingpage.css
  style.css
Labels: approved

#24 23 review page home
  2homepage/2homepage.css
  2homepage/2homepage.html
  2homepage/media.css
  images/iconhome.png
Labels: approved

#27 update css files
  2homepage/2homepage.css
  2homepage/media.css
Labels: approved

#28 Send money
  4sendmoneypage/4sendmoneypage.css
  4sendmoneypage/4sendmoneypage.html
  4sendmoneypage/media.css
  images/Pagination.png
Labels: approved

#30 editing the style of the landing page
  README.md
  medialandingpage.css
  style.css
Labels: approved

#34 update css files
  .vscode/settings.json
  2homepage/2homepage.css
  2homepage/media.css
Labels: approved

#32 update the wallet page
  3walletpage/3walletpage.css
  3walletpage/3walletpage.html
  images/Floating_Action_Button.png
  images/home.png
Labels: awaiting-review

#36 update all project
  2homepage/2homepage.html
  3walletpage/3walletpage.css
  3walletpage/3walletpage.html
  3walletpage/responsive.css
  4sendmoneypage/4sendmoneypage.html
  images/profile.png
Labels: approved

#26 writing the read me file for the project
  style.css
Labels: approved
